[package]
name = "evaera/matter"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["example", "docs", "Packages", ".moonwave", "build", "pages", "tests"]

[dependencies]
TestEZ = "roblox/testez@0.4.1"
Llama = "shanebutt/llama@1.1.0"